---
- hosts: localhost
  connection: local
  tasks:
    - name: Get compute region
      shell: gcloud config get-value compute/region
      register: COMPUTE_REGION
      changed_when: false

    - name: Get static ip address
      shell: >
        gcloud compute addresses describe kubernetes-the-hard-way
        --region {{ COMPUTE_REGION.stdout }}
        --format 'value(address)'
      register: KUBERNETES_PUBLIC_ADDRESS
      changed_when: false

    - name: Read current .kube/config
      set_fact: kubeconfig={{ lookup('file', '{{ ansible_env.HOME }}/.kube/config') }}

    - name: Create Admin Kubernetes Configuration File
      shell: >
        kubectl config set-cluster kubernetes-the-hard-way
        --certificate-authority=certs/ca.pem
        --embed-certs=true
        --server=https://{{ KUBERNETES_PUBLIC_ADDRESS.stdout }}:6443 &&
        kubectl config set-credentials admin
        --client-certificate=certs/admin.pem
        --client-key=certs/admin-key.pem &&
        kubectl config set-context kubernetes-the-hard-way
        --cluster=kubernetes-the-hard-way
        --user=admin &&
        kubectl config use-context kubernetes-the-hard-way
      when: "'current-context: kubernetes-the-hard-way' not in kubeconfig"
